services:
  postgres:
    container_name: pg_service
    image: postgres
    environment:
      POSTGRES_USER: khaoula
      POSTGRES_PASSWORD: khaoula
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_service
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    restart: always
  mongodb:
    container_name: mongodb_service
    image : mongo
    ports:
      - 8083:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: khaoula
      MONGO_INITDB_ROOT_PASSWORD: khaoula
  mongo-express:
    container_name: mongo_express_service
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: khaoula
      ME_CONFIG_MONGODB_ADMINPASSWORD: khaoula
      ME_CONFIG_MONGODB_SERVER: mongodb
  mail-dev:
    container_name: maildev_service
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025



networks:
  microservices-net:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  mongo:
